apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-issuer-controller
  namespace: dummy-issuer
spec:
  selector:
    matchLabels:
      issuer-component: controller
  replicas: 1
  template:
    metadata:
      labels:
        issuer-component: controller
    spec:
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 5
      volumes:
      - name: script-cm
        configMap:
          name: script-cm
          defaultMode: 0555
      containers:
      - name: controller
        command:
        - /scripts/controller.sh
        image: wbitt/network-multitool:latest
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: script-cm
          mountPath: /scripts